import Head from "next/head";
import Link from "next/link";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
// import deved from "../public/dev-ed-wave.png";
import code from "../public/code.png";
import design from "../public/design.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import ajmal from "../public/ajmal.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Ajmal's Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="font-raleway bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-greatvibe font-bold tracking-widest  text-4xl ">
              Portofolio
            </h1>
            <ul className="flex items-center mx-2">
              <li className="">
                <BsFillMoonStarsFill
                  title="Change Mode"
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <Link href="components/resume">
                  {/* <a target="_blank" > */}
                  <label
                    title="Resume"
                    className="bg-gradient-to-r cursor-pointer from-cyan-500 text- to-teal-500 text-white  px-4 py-2 border-none rounded-md ml-1 sm:ml-8"
                  >
                    Resume
                  </label>
                  {/* </a> */}
                </Link>
              </li>
            </ul>
          </nav>
          <div className="text-center sm:p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              AJMAL ALI
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Web Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              I want to make really cool and easy-to-use websites as a web
              developer. I like making websites that people will enjoy using.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <AiFillGithub
                title="GitHub"
                className="cursor-pointer"
                onClick={() => {
                  location.assign("https://github.com/ajmal117");
                }}
              />

              <AiFillLinkedin
                title="LinkedIn"
                className="cursor-pointer"
                onClick={() => {
                  location.assign(
                    "https://www.linkedin.com/in/ajmal-ali-3012651b7/"
                  );
                }}
              />
              <Link href="components/twitterPage">
                <AiFillTwitterCircle
                  className="cursor-pointer"
                  title="twitter"
                />
              </Link>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full shadow-md shadow-sky-500  w-56 h-60  relative overflow-hidden mt-10 md:h-96 md:w-96">
              <Image src={ajmal} className="" layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Experience</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              <b>React.js:</b> Developed dynamic user interfaces with React,
              leveraging component-based architecture and state management to
              create responsive and interactive web applications pages.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              <b> Next.js:</b> Built server-rendered React applications using
              Next.js, benefiting from its automatic code splitting and routing
              capabilities for improved performance and SEO, while maintaining a
              smooth development experience.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={design} />

              <p className="py-2">React JS</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <div className="mt-6">
                <Image src={code} />
              </div>

              <p className="py-2 pt-12">Next JS</p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Tools :</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I have extensive experience working with a wide range of frontend
              web development tools that are pivotal in creating seamless and
              engaging user experiences. Proficient in utilizing modern
              libraries React js.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Web development has been like bringing my ideas to life on the
              internet. I mix design and coding to make websites fun to use.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 p-7 border-1 rounded-lg shadow-lg shadow-yellow-400">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
              />
            </div>
            <div className="basis-1/3 flex-1 p-7  border-1 rounded-lg shadow-lg shadow-blue-400 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
              />
            </div>
            <div className="basis-1/3 flex-1 p-7  border-1 rounded-lg shadow-lg shadow-orange-400 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
              />
            </div>

            <div className="basis-1/3 flex-1 p-7  border-1 rounded-lg shadow-lg shadow-blue-400 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}
              />
            </div>
            <div className="basis-1/3 flex-1 p-7  border-1 rounded-lg shadow-lg shadow-blue-400 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web5}
              />
            </div>
            <div className="basis-1/3 flex-1 p-7  border-1 rounded-lg shadow-lg shadow-red-400 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web6}
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
